import {
  DashboardKPIs,
  SalesTrendPoint,
  StockHealthSummary,
  RecommendedOrder,
  TopProduct,
  SlowMovingProduct,
  BusinessInsight,
} from "@/types/dashboard";
import { Product, Supplier, StockAlert } from "@/types/inventory";
import { Sale } from "@/types/sales";

export const demoKPIs: DashboardKPIs = {
  todaySales: 48920,
  todaySalesChange: 14.2,
  billsCount: 142,
  billsChange: 8.5,
  avgBillValue: 344,
  itemsSold: 388,
  inventoryValue: 845200,
  skuCount: 420,
};

export const demoHourlySales: SalesTrendPoint[] = [
  { timeLabel: "09:00", sales: 2100, target: 1800, bills: 6 },
  { timeLabel: "10:00", sales: 4350, target: 3500, bills: 12 },
  { timeLabel: "11:00", sales: 6800, target: 5000, bills: 19 },
  { timeLabel: "12:00", sales: 5200, target: 4500, bills: 15 },
  { timeLabel: "13:00", sales: 3400, target: 3800, bills: 10 },
  { timeLabel: "14:00", sales: 2900, target: 2800, bills: 8 },
  { timeLabel: "15:00", sales: 4100, target: 3600, bills: 11 },
  { timeLabel: "16:00", sales: 5600, target: 4800, bills: 16 },
  { timeLabel: "17:00", sales: 7400, target: 6000, bills: 22 },
  { timeLabel: "18:00", sales: 8900, target: 7500, bills: 26 },
  { timeLabel: "19:00", sales: 9400, target: 8200, bills: 28 },
  { timeLabel: "20:00", sales: 6870, target: 6500, bills: 21 },
];

export const demoStockHealth: StockHealthSummary = {
  totalSkus: 420,
  healthyCount: 344,
  lowStockCount: 46,
  outOfStockCount: 17,
  overstockedCount: 13,
  healthyPercentage: 82,
};

export const demoRecommendedOrders: RecommendedOrder[] = [
  {
    id: "ord-1",
    productId: "prod-101",
    productName: "Aashirvaad Shudh Chakki Atta 10kg",
    sku: "ATT-10K-01",
    category: "Staples & Grains",
    supplierName: "Apex FMCG Distributors",
    currentStock: 4,
    reorderPoint: 15,
    recommendedQty: 25,
    unit: "Bags",
    estimatedCost: 10875,
    urgency: "critical",
    stockoutRiskDays: 1,
  },
  {
    id: "ord-2",
    productId: "prod-102",
    productName: "Tata Salt Vacuum Evaporated 1kg",
    sku: "SLT-01K-02",
    category: "Spices & Seasoning",
    supplierName: "Bharat Wholesale Traders",
    currentStock: 6,
    reorderPoint: 24,
    recommendedQty: 50,
    unit: "Pks",
    estimatedCost: 1150,
    urgency: "critical",
    stockoutRiskDays: 2,
  },
  {
    id: "ord-3",
    productId: "prod-103",
    productName: "Fortune Sunlite Refined Sunflower Oil 1L",
    sku: "OIL-01L-03",
    category: "Edible Oils",
    supplierName: "Apex FMCG Distributors",
    currentStock: 12,
    reorderPoint: 30,
    recommendedQty: 40,
    unit: "Pouches",
    estimatedCost: 5200,
    urgency: "moderate",
    stockoutRiskDays: 3,
  },
  {
    id: "ord-4",
    productId: "prod-104",
    productName: "Amul Taaza Homogenised Toned Milk 1L",
    sku: "MLK-01L-04",
    category: "Dairy & Chilled",
    supplierName: "Metro Chilled Logistics",
    currentStock: 8,
    reorderPoint: 25,
    recommendedQty: 30,
    unit: "Tetra",
    estimatedCost: 2040,
    urgency: "critical",
    stockoutRiskDays: 1,
  },
  {
    id: "ord-5",
    productId: "prod-105",
    productName: "Surf Excel Easy Wash Detergent Powder 1kg",
    sku: "DET-01K-05",
    category: "Household & Cleaning",
    supplierName: "Hindustan Retail Direct",
    currentStock: 14,
    reorderPoint: 20,
    recommendedQty: 20,
    unit: "Pks",
    estimatedCost: 2800,
    urgency: "scheduled",
    stockoutRiskDays: 5,
  },
];

export const demoTopProducts: TopProduct[] = [
  {
    id: "tp-1",
    name: "Amul Butter Pasteurized 500g",
    category: "Dairy & Chilled",
    unitsSold: 38,
    revenue: 10450,
    velocity: "38 units/day",
    marginPercentage: 16.5,
  },
  {
    id: "tp-2",
    name: "Aashirvaad Shudh Chakki Atta 10kg",
    category: "Staples & Grains",
    unitsSold: 21,
    revenue: 9975,
    velocity: "21 units/day",
    marginPercentage: 12.0,
  },
  {
    id: "tp-3",
    name: "Fortune Sunlite Refined Oil 1L",
    category: "Edible Oils",
    unitsSold: 42,
    revenue: 5880,
    velocity: "42 units/day",
    marginPercentage: 14.8,
  },
  {
    id: "tp-4",
    name: "Tata Tea Gold 500g",
    category: "Beverages",
    unitsSold: 18,
    revenue: 5400,
    velocity: "18 units/day",
    marginPercentage: 22.4,
  },
  {
    id: "tp-5",
    name: "Maggi 2-Minute Noodles 12-Pack",
    category: "Snacks & Instant",
    unitsSold: 28,
    revenue: 4480,
    velocity: "28 units/day",
    marginPercentage: 18.2,
  },
];

export const demoSlowMovingProducts: SlowMovingProduct[] = [
  {
    id: "sm-1",
    name: "Specialty Organic Quinoa Seeds 500g",
    category: "Organic Staples",
    daysWithoutSale: 46,
    tiedCapital: 6800,
    currentStock: 17,
    unit: "Pks",
    status: "critical_deadstock",
  },
  {
    id: "sm-2",
    name: "Imported Dijon Mustard 250g",
    category: "Gourmet Condiments",
    daysWithoutSale: 39,
    tiedCapital: 4250,
    currentStock: 11,
    unit: "Jars",
    status: "critical_deadstock",
  },
  {
    id: "sm-3",
    name: "Premium Rosemary Infused Olive Oil 500ml",
    category: "Edible Oils",
    daysWithoutSale: 28,
    tiedCapital: 5400,
    currentStock: 9,
    unit: "Bottles",
    status: "slow",
  },
  {
    id: "sm-4",
    name: "Sugar-Free Dark Chocolate Syrup 300g",
    category: "Baking & Desserts",
    daysWithoutSale: 24,
    tiedCapital: 3120,
    currentStock: 12,
    unit: "Bottles",
    status: "slow",
  },
];

export const demoInsights: BusinessInsight[] = [
  {
    id: "ins-1",
    title: "Stockout Risk on Top Fast Mover",
    description: "Aashirvaad Atta 10kg will deplete in <24 hours at current sales velocity. 25 bags reorder suggested.",
    type: "alert",
    metricImpact: "Potential ₹11,875 loss if missed",
    actionText: "Generate Purchase Order",
    actionHref: "/inventory/reorders",
  },
  {
    id: "ins-2",
    title: "Capital Locked in Deadstock",
    description: "4 specialty items haven't recorded a sale in 30+ days, tying up ₹19,570 in working capital.",
    type: "warning",
    metricImpact: "₹19,570 illiquid stock",
    actionText: "Review Markdown Promo",
    actionHref: "/inventory/products",
  },
  {
    id: "ins-3",
    title: "Peak Hour Velocity Shift",
    description: "Evening peak shifted to 18:00–20:00 today. UPI settlements accounted for 74% of revenue.",
    type: "healthy",
    metricImpact: "Digital payments +21%",
    actionText: "View Sales History",
    actionHref: "/sales/history",
  },
];

export const demoSuppliers: Supplier[] = [
  {
    id: "sup-1",
    shopId: "shop-demo-1",
    name: "Apex FMCG Distributors",
    phone: "+91 98201 44521",
    email: "ramesh@apexfmcg.in",
    address: "Plot 12, APMC Wholesale Yard, Vashi, Navi Mumbai 400703",
    leadTime: 2,
    minOrderQuantity: 10,
    notes: "Primary supplier for branded atta, pulses, and packaged groceries.",
  },
  {
    id: "sup-2",
    shopId: "shop-demo-1",
    name: "Bharat Wholesale Traders",
    phone: "+91 94150 99881",
    email: "orders@bharatwholesale.com",
    address: "45 Commercial Gali, Sadar Bazaar, Delhi 110006",
    leadTime: 1,
    minOrderQuantity: 25,
    notes: "Spices, salt, and loose commodities.",
  },
  {
    id: "sup-3",
    shopId: "shop-demo-1",
    name: "Metro Chilled Logistics",
    phone: "+91 98840 12345",
    email: "dairy@metrologistics.in",
    address: "Cold Chain Hub 4, Peenya Industrial Area, Bengaluru 560058",
    leadTime: 1,
    minOrderQuantity: 15,
    notes: "Dairy products, butter, and frozen items.",
  },
];

export const demoCategories = [
  "Staples & Grains",
  "Dairy & Chilled",
  "Edible Oils",
  "Snacks & Instant",
  "Spices & Seasoning",
  "Beverages",
  "Household & Cleaning",
  "Personal Care",
];
